### ISSUE TITLE
babel 5.0

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/ember-jobs#28]
- [ ] pending fix to async/await https://github.com/babel/babel/issues/1174

**Comment by stefanpenner** [comment]
cc @teddyzeenny you may run into this when you upgrade the inspector

**Comment by teddyzeenny** [comment]
@stefanpenner I worked around it by naming async functions:
```js
test('description', async function t() {})
```

**Comment by stefanpenner** [comment]
nice!

**Comment by stefanpenner** [comment]
used the workaround
