### ISSUE TITLE
Transpilation error - this.store.find is not a function

### ISSUE THREAD

**Issue by brianmbutler** [stefanpenner/ember-jobs#33]
Stefan,

From our brief slack conversation.    Trying your technique in the index.route with the async functions to hash the model, both Chrome and Safari throw an error, roughly:

    Error while processing route: index this.store.find is not a function TypeError: this.store.find is not a function

It seems to be something with this line during the regeneration:

      while (1) switch (context$1$0.prev = context$1$0.next) {
          case 0:
            context$1$0.next = 2;
            return regeneratorRuntime.awrap(this.store.find('employee'));

I did see that regenerator has been updated to 0.8.30, somewhere around 0.8.28 had the issue.

**Comment by stefanpenner** [comment]
Awesome thanks for the issue. I hope to get to this later this week

**Comment by brianmbutler** [comment]
Wondering if it is because the async is inside a normal function.

**Comment by brianmbutler** [comment]
I think I fixed this @stefanpenner I didn't have the regenerator runtime declared in my index.html

**Comment by stefanpenner** [comment]
Ah. That makes sense. We will soon do that automatic for our users

**Comment by pnosko** [comment]
I have the same problem, could you please be kind enough to provide a workaround? I don't know how to add generator runtime to index.html. Thanks!
